importReactfrom'react';
import{
View,Text,StyleSheet,ScrollView,TouchableOpacity,Share,
}from'react-native';
import{Ionicons}from'@expo/vector-icons';
import{colors,spacing,fontSize}from'../theme';

exportdefaultfunctionReceiptScreen({route,navigation}){
const{receipt}=route.params;
constisContribution=receipt.receipt_type==='contribution';
constamount=isContribution?receipt.payment?.amount:receipt.payout?.amount;
constdate=newDate(receipt.issued_at).toLocaleString();

consthandleShare=async()=>{
constlines=[
`💜ViaReceipt`,
`─────────────────────`,
`Type:${isContribution?'Contribution':'Payout'}`,
`ReceiptNo:${receipt.receipt_number}`,
receipt.transaction_id?`Transaction:${receipt.transaction_id}`:'',
`Amount:${Number(amount).toLocaleString()}XAF`,
`Status:${receipt.status}`,
`Date:${date}`,
`─────────────────────`,
`Member:${receipt.member.name}`,
`Phone:${receipt.member.phone}`,
`Group:${receipt.group.name}`,
isContribution?`Method:${receipt.payment.method}`:`Position:#${receipt.payout.position}`,
`─────────────────────`,
`ThankyouforusingVia🙏`,
].filter(Boolean).join('\n');

awaitShare.share({message:lines});
};

return(
<ScrollViewstyle={styles.container}contentContainerStyle={styles.content}>

{/*Header*/}
<Viewstyle={styles.header}>
<Textstyle={styles.logo}>💜Via</Text>
<Viewstyle={styles.typeBadge}>
<Textstyle={styles.typeBadgeText}>
{isContribution?'💳ContributionReceipt':'💰PayoutReceipt'}
</Text>
</View>
</View>

{/*Status*/}
<Viewstyle={[styles.statusBanner,receipt.status==='completed'?styles.statusSuccess:styles.statusPending]}>
<Ionicons
name={receipt.status==='completed'?'checkmark-circle':'time'}
size={18}
color={receipt.status==='completed'?'#16A34A':'#CA8A04'}
/>
<Textstyle={[styles.statusText,{color:receipt.status==='completed'?'#16A34A':'#CA8A04'}]}>
{receipt.status==='completed'?'PaymentConfirmed':receipt.status}
</Text>
</View>

{/*Amount*/}
<Viewstyle={styles.amountSection}>
<Textstyle={styles.amountLabel}>{isContribution?'AmountPaid':'AmountReceived'}</Text>
<Textstyle={styles.amount}>{Number(amount).toLocaleString()}XAF</Text>
</View>

{/*Details*/}
<Viewstyle={styles.detailsCard}>
<Rowlabel="ReceiptNo."value={receipt.receipt_number}mono/>
{receipt.transaction_id&&<Rowlabel="TransactionID"value={receipt.transaction_id}mono/>}
<Rowlabel="Date"value={date}/>
<Rowlabel="Member"value={receipt.member.name}/>
<Rowlabel="Phone"value={receipt.member.phone}/>
<Rowlabel="Group"value={receipt.group.name}/>
<Rowlabel="Cycle"value={receipt.group.cycle}capitalize/>
{isContribution&&(
<>
<Rowlabel="PaymentMethod"value={receipt.payment.method}/>
<Rowlabel="CycleNumber"value={`#${receipt.payment.cycle_number}`}/>
</>
)}
{!isContribution&&(
<>
<Rowlabel="QueuePosition"value={`#${receipt.payout.position}`}/>
{receipt.payout.payout_date&&(
<Rowlabel="PayoutDate"value={newDate(receipt.payout.payout_date).toLocaleDateString()}/>
)}
<Rowlabel="MembersinGroup"value={String(receipt.group.member_count)}/>
</>
)}
</View>

{/*Footernote*/}
<Viewstyle={styles.footer}>
<Textstyle={styles.footerText}>ThankyouforusingVia🙏</Text>
<Textstyle={styles.footerSub}>Keepthisreceiptforyourrecords.</Text>
</View>

{/*Actions*/}
<Viewstyle={styles.actions}>
<TouchableOpacitystyle={styles.shareBtn}onPress={handleShare}>
<Ioniconsname="share-outline"size={18}color={colors.primary}/>
<Textstyle={styles.shareBtnText}>Share</Text>
</TouchableOpacity>
<TouchableOpacitystyle={styles.doneBtn}onPress={()=>navigation.goBack()}>
<Textstyle={styles.doneBtnText}>Done</Text>
</TouchableOpacity>
</View>

</ScrollView>
);
}

functionRow({label,value,mono,capitalize}){
return(
<Viewstyle={styles.row}>
<Textstyle={styles.rowLabel}>{label}</Text>
<Textstyle={[styles.rowValue,mono&&styles.mono,capitalize&&styles.capitalize]}numberOfLines={1}>
{value}
</Text>
</View>
);
}

conststyles=StyleSheet.create({
container:{flex:1,backgroundColor:colors.background},
content:{padding:spacing.md,paddingBottom:40},

header:{
backgroundColor:colors.primary,
borderRadius:16,
padding:spacing.md,
flexDirection:'row',
justifyContent:'space-between',
alignItems:'center',
marginBottom:spacing.sm,
},
logo:{fontSize:fontSize.lg,fontWeight:'700',color:colors.white},
typeBadge:{
backgroundColor:'rgba(255,255,255,0.2)',
paddingHorizontal:10,
paddingVertical:4,
borderRadius:20,
},
typeBadgeText:{fontSize:11,fontWeight:'600',color:colors.white},

statusBanner:{
flexDirection:'row',
alignItems:'center',
gap:8,
padding:spacing.sm,
borderRadius:10,
marginBottom:spacing.sm,
},
statusSuccess:{backgroundColor:'#DCFCE7'},
statusPending:{backgroundColor:'#FEF9C3'},
statusText:{fontSize:fontSize.md,fontWeight:'600'},

amountSection:{
backgroundColor:colors.white,
borderRadius:16,
padding:spacing.lg,
alignItems:'center',
marginBottom:spacing.sm,
},
amountLabel:{fontSize:fontSize.sm,color:colors.subtext,marginBottom:4},
amount:{fontSize:40,fontWeight:'800',color:colors.primary,letterSpacing:-1},

detailsCard:{
backgroundColor:colors.white,
borderRadius:16,
padding:spacing.md,
marginBottom:spacing.sm,
},
row:{
flexDirection:'row',
justifyContent:'space-between',
alignItems:'center',
paddingVertical:10,
borderBottomWidth:1,
borderBottomColor:colors.border,
},
rowLabel:{fontSize:fontSize.sm,color:colors.subtext,flex:1},
rowValue:{fontSize:fontSize.sm,fontWeight:'600',color:colors.text,flex:1,textAlign:'right'},
mono:{fontFamily:'monospace',fontSize:11},
capitalize:{textTransform:'capitalize'},

footer:{
alignItems:'center',
backgroundColor:colors.white,
borderRadius:16,
padding:spacing.md,
marginBottom:spacing.md,
},
footerText:{fontSize:fontSize.md,color:colors.text,fontWeight:'500'},
footerSub:{fontSize:fontSize.sm,color:colors.subtext,marginTop:2},

actions:{flexDirection:'row',gap:12},
shareBtn:{
flex:1,
flexDirection:'row',
alignItems:'center',
justifyContent:'center',
gap:6,
padding:13,
borderRadius:12,
borderWidth:1.5,
borderColor:colors.primary,
},
shareBtnText:{fontSize:fontSize.md,fontWeight:'600',color:colors.primary},
doneBtn:{
flex:1,
padding:13,
borderRadius:12,
backgroundColor:colors.primary,
alignItems:'center',
},
doneBtnText:{fontSize:fontSize.md,fontWeight:'600',color:colors.white},
});
