import React, { createContext, useContext, useState } from 'react';

export const LANGUAGES = [
  { id: 'en', label: 'English',    nativeLabel: 'English',    flag: '🇬🇧' },
  { id: 'fr', label: 'French',     nativeLabel: 'Français',   flag: '🇫🇷' },
  { id: 'es', label: 'Spanish',    nativeLabel: 'Español',    flag: '🇪🇸' },
  { id: 'pt', label: 'Portuguese', nativeLabel: 'Português',  flag: '🇵🇹' },
  { id: 'ar', label: 'Arabic',     nativeLabel: 'العربية',    flag: '🇸🇦' },
  { id: 'sw', label: 'Swahili',    nativeLabel: 'Kiswahili',  flag: '🇰🇪' },
  { id: 'ha', label: 'Hausa',      nativeLabel: 'Hausa',      flag: '🇳🇬' },
  { id: 'yo', label: 'Yoruba',     nativeLabel: 'Yorùbá',     flag: '🇳🇬' },
];

const en = {
  dashboard: 'Dashboard', groups: 'Groups', notifications: 'Notifications',
  profile: 'Profile', settings: 'Settings',
  hello: 'Hello', trustScore: 'Trust Score', totalGroups: 'Total Groups',
  active: 'Active', forming: 'Forming', role: 'Role', myGroups: 'My Groups',
  createGroup: '+ Create Group', browseGroups: 'Browse Groups',
  noGroupsYet: 'No groups yet.', loading: 'Loading...',
  verifyBannerTitle: 'Complete your identity verification',
  verifyBannerDesc: 'You need to verify your ID or Passport before creating groups, joining, or contributing.',
  verifyNow: 'Verify Now',
  allGroups: 'All Groups', searchGroups: 'Search groups...', noGroupsFound: 'No groups found',
  members: 'members', back: '← Back', joinGroup: 'Join Group', contribute: 'Contribute',
  viewPayouts: 'View Payouts', startGroup: 'Start Group', inviteMembers: 'Invite Members',
  inviteHint: "Share this link with anyone you want to invite. They'll need admin approval after joining.",
  generateInviteLink: '🔗 Generate Invite Link', copy: 'Copy', copied: '✓ Copied!',
  name: 'Name', phone: 'Phone', trustScoreCol: 'Trust Score', status: 'Status',
  action: 'Action', approve: 'Approve', you: '(You)', groupNotFound: 'Group not found',
  joinRequestSent: 'Join request sent!', groupStarted: 'Group started!',
  editProfile: 'Edit Profile', fullName: 'Full Name', saveChanges: 'Save Changes',
  saving: 'Saving...', profileUpdated: 'Profile updated successfully!',
  updateFailed: 'Update failed', accountInfo: 'Account Info', verified: 'Verified',
  yes: '✓ Yes', no: '✗ No', signOut: 'Sign Out',
  notificationsTitle: 'Notifications', unread: 'unread',
  noNotifications: 'No notifications yet', markRead: 'Mark read',
  welcomeBack: 'Welcome Back', signInSubtitle: 'Sign in to your account',
  phoneNumber: 'Phone Number', password: 'Password', signingIn: 'Signing in...',
  signIn: 'Sign In', noAccount: "Don't have an account?", register: 'Register',
  createAccount: 'Create Account', registerSubtitle: 'Join Via and start saving together',
  passwordOptional: 'Password (optional)', passwordHint: 'Min 6 characters',
  registering: 'Registering...', alreadyHaveAccount: 'Already have an account?',
  verifyPhone: 'Verify Phone', otpSentTo: 'Enter the 6-digit code sent to',
  otpCode: 'OTP Code', verifying: 'Verifying...', verify: 'Verify',
  backToLogin: '← Back to Login', createGroupTitle: 'Create Njangi Group',
  groupName: 'Group Name *', description: 'Description',
  descriptionPlaceholder: 'About this group...', contributionAmount: 'Contribution Amount (XAF) *',
  maxMembers: 'Max Members', contributionCycle: 'Contribution Cycle',
  cancel: 'Cancel', creating: 'Creating...', failedToCreate: 'Failed to create group',
  makeContribution: 'Make Contribution', amountToPay: 'Amount to Pay',
  selectPaymentMethod: 'Select Payment Method', processing: 'Processing...',
  pay: 'Pay', paymentFailed: 'Payment failed',
  payoutQueue: 'Payout Queue', noPayoutYet: 'No payout queue yet. Start the group first.',
  settingsTitle: 'Settings', appearance: 'Appearance', theme: 'Theme',
  themeDesc: 'Switch between light and dark mode', colorPalette: 'Color Palette',
  lightMode: 'LIGHT MODE', darkMode: 'DARK MODE', account: 'Account',
  logOut: 'Log Out', logOutConfirm: 'Log out?',
  logOutDesc: 'Are you sure you want to log out of Via?',
  yesLogOut: 'Yes, Log Out', language: 'Language',
  languageDesc: 'Choose your preferred language',
  identityVerification: 'Identity Verification',
  identityVerificationDesc: 'Required before creating groups, joining, or contributing',
  chooseDocType: 'Choose Document Type',
  chooseDocTypeDesc: 'Select the government-issued document you want to use for verification.',
  passport: 'Passport', passportDesc: 'International travel document',
  nationalId: 'National ID', nationalIdDesc: 'Government-issued ID card',
  docPhotoHint: 'Upload a clear, well-lit photo of your', changePhoto: 'Change photo',
  continueToFaceScan: 'Continue to Face Scan →', faceVerification: 'Face Verification',
  faceVerificationDesc: "Take a selfie. We'll compare it against your document photo to confirm your identity.",
  openCamera: 'Click to open camera', cameraHint: 'Make sure your face is well-lit and clearly visible',
  positionFace: 'Position your face inside the oval', captureSelfie: '📸 Capture Selfie',
  captured: '📸 Captured', retakeSelfie: 'Retake selfie', verifyIdentity: 'Verify Identity →',
  analyzingTitle: 'Analyzing your identity...', identityVerified: 'Identity Verified!',
  identityVerifiedDesc2: 'has been verified successfully. You can now create groups, join, and contribute.',
  goToDashboard: 'Go to Dashboard →', document: 'Document', faceScan: 'Face Scan',
  youreInvited: "You've been invited!", invitedDesc: 'You were invited to join a Via savings group.',
  acceptInvite: 'Accept Invite', requestSent: 'Request Sent!',
  requestSentDesc: 'Your request to join', requestSentDesc2: 'has been sent. An admin will review and approve it shortly.',
  invalidInvite: 'Invalid or expired invite link.',
  chooseLanguage: 'Choose your language',
};

const fr = {
  dashboard: 'Tableau de bord', groups: 'Groupes', notifications: 'Notifications',
  profile: 'Profil', settings: 'Paramètres',
  hello: 'Bonjour', trustScore: 'Score de confiance', totalGroups: 'Total groupes',
  active: 'Actif', forming: 'En formation', role: 'Rôle', myGroups: 'Mes groupes',
  createGroup: '+ Créer un groupe', browseGroups: 'Parcourir les groupes',
  noGroupsYet: 'Aucun groupe pour le moment.', loading: 'Chargement...',
  verifyBannerTitle: 'Complétez votre vérification d\'identité',
  verifyBannerDesc: 'Vous devez vérifier votre pièce d\'identité ou passeport avant de créer des groupes, rejoindre ou contribuer.',
  verifyNow: 'Vérifier maintenant',
  allGroups: 'Tous les groupes', searchGroups: 'Rechercher des groupes...', noGroupsFound: 'Aucun groupe trouvé',
  members: 'membres', back: '← Retour', joinGroup: 'Rejoindre', contribute: 'Contribuer',
  viewPayouts: 'Voir les paiements', startGroup: 'Démarrer le groupe', inviteMembers: 'Inviter des membres',
  inviteHint: "Partagez ce lien avec toute personne que vous souhaitez inviter. Elle devra être approuvée par un administrateur.",
  generateInviteLink: '🔗 Générer un lien d\'invitation', copy: 'Copier', copied: '✓ Copié!',
  name: 'Nom', phone: 'Téléphone', trustScoreCol: 'Score de confiance', status: 'Statut',
  action: 'Action', approve: 'Approuver', you: '(Vous)', groupNotFound: 'Groupe introuvable',
  joinRequestSent: 'Demande d\'adhésion envoyée!', groupStarted: 'Groupe démarré!',
  editProfile: 'Modifier le profil', fullName: 'Nom complet', saveChanges: 'Enregistrer',
  saving: 'Enregistrement...', profileUpdated: 'Profil mis à jour avec succès!',
  updateFailed: 'Échec de la mise à jour', accountInfo: 'Informations du compte', verified: 'Vérifié',
  yes: '✓ Oui', no: '✗ Non', signOut: 'Se déconnecter',
  notificationsTitle: 'Notifications', unread: 'non lues',
  noNotifications: 'Aucune notification pour le moment', markRead: 'Marquer comme lu',
  welcomeBack: 'Bon retour', signInSubtitle: 'Connectez-vous à votre compte',
  phoneNumber: 'Numéro de téléphone', password: 'Mot de passe', signingIn: 'Connexion...',
  signIn: 'Se connecter', noAccount: "Vous n'avez pas de compte?", register: 'S\'inscrire',
  createAccount: 'Créer un compte', registerSubtitle: 'Rejoignez Via et épargnez ensemble',
  passwordOptional: 'Mot de passe (optionnel)', passwordHint: 'Min 6 caractères',
  registering: 'Inscription...', alreadyHaveAccount: 'Vous avez déjà un compte?',
  verifyPhone: 'Vérifier le téléphone', otpSentTo: 'Entrez le code à 6 chiffres envoyé à',
  otpCode: 'Code OTP', verifying: 'Vérification...', verify: 'Vérifier',
  backToLogin: '← Retour à la connexion', createGroupTitle: 'Créer un groupe Njangi',
  groupName: 'Nom du groupe *', description: 'Description',
  descriptionPlaceholder: 'À propos de ce groupe...', contributionAmount: 'Montant de contribution (XAF) *',
  maxMembers: 'Membres maximum', contributionCycle: 'Cycle de contribution',
  cancel: 'Annuler', creating: 'Création...', failedToCreate: 'Échec de la création du groupe',
  makeContribution: 'Faire une contribution', amountToPay: 'Montant à payer',
  selectPaymentMethod: 'Sélectionner le mode de paiement', processing: 'Traitement...',
  pay: 'Payer', paymentFailed: 'Échec du paiement',
  payoutQueue: 'File de paiement', noPayoutYet: 'Pas encore de file de paiement. Démarrez le groupe d\'abord.',
  settingsTitle: 'Paramètres', appearance: 'Apparence', theme: 'Thème',
  themeDesc: 'Basculer entre le mode clair et sombre', colorPalette: 'Palette de couleurs',
  lightMode: 'MODE CLAIR', darkMode: 'MODE SOMBRE', account: 'Compte',
  logOut: 'Se déconnecter', logOutConfirm: 'Se déconnecter?',
  logOutDesc: 'Êtes-vous sûr de vouloir vous déconnecter de Via?',
  yesLogOut: 'Oui, se déconnecter', language: 'Langue',
  languageDesc: 'Choisissez votre langue préférée',
  identityVerification: 'Vérification d\'identité',
  identityVerificationDesc: 'Requis avant de créer des groupes, rejoindre ou contribuer',
  chooseDocType: 'Choisir le type de document',
  chooseDocTypeDesc: 'Sélectionnez le document officiel que vous souhaitez utiliser pour la vérification.',
  passport: 'Passeport', passportDesc: 'Document de voyage international',
  nationalId: 'Carte d\'identité', nationalIdDesc: 'Carte d\'identité nationale',
  docPhotoHint: 'Téléchargez une photo claire de votre', changePhoto: 'Changer la photo',
  continueToFaceScan: 'Continuer vers la reconnaissance faciale →', faceVerification: 'Vérification faciale',
  faceVerificationDesc: "Prenez un selfie. Nous le comparerons à votre photo de document pour confirmer votre identité.",
  openCamera: 'Cliquez pour ouvrir la caméra', cameraHint: 'Assurez-vous que votre visage est bien éclairé',
  positionFace: 'Positionnez votre visage dans l\'ovale', captureSelfie: '📸 Prendre un selfie',
  captured: '📸 Capturé', retakeSelfie: 'Reprendre le selfie', verifyIdentity: 'Vérifier l\'identité →',
  analyzingTitle: 'Analyse de votre identité...', identityVerified: 'Identité vérifiée!',
  identityVerifiedDesc2: 'a été vérifié avec succès. Vous pouvez maintenant créer des groupes, rejoindre et contribuer.',
  goToDashboard: 'Aller au tableau de bord →', document: 'Document', faceScan: 'Scan facial',
  youreInvited: "Vous êtes invité!", invitedDesc: 'Vous avez été invité à rejoindre un groupe d\'épargne Via.',
  acceptInvite: 'Accepter l\'invitation', requestSent: 'Demande envoyée!',
  requestSentDesc: 'Votre demande pour rejoindre', requestSentDesc2: 'a été envoyée. Un administrateur l\'examinera et l\'approuvera bientôt.',
  invalidInvite: 'Lien d\'invitation invalide ou expiré.',
  chooseLanguage: 'Choisissez votre langue',
};

const es = {
  dashboard: 'Panel', groups: 'Grupos', notifications: 'Notificaciones',
  profile: 'Perfil', settings: 'Configuración',
  hello: 'Hola', trustScore: 'Puntuación de confianza', totalGroups: 'Total de grupos',
  active: 'Activo', forming: 'Formando', role: 'Rol', myGroups: 'Mis grupos',
  createGroup: '+ Crear grupo', browseGroups: 'Explorar grupos',
  noGroupsYet: 'Aún no hay grupos.', loading: 'Cargando...',
  verifyBannerTitle: 'Completa tu verificación de identidad',
  verifyBannerDesc: 'Debes verificar tu ID o pasaporte antes de crear grupos, unirte o contribuir.',
  verifyNow: 'Verificar ahora',
  allGroups: 'Todos los grupos', searchGroups: 'Buscar grupos...', noGroupsFound: 'No se encontraron grupos',
  members: 'miembros', back: '← Atrás', joinGroup: 'Unirse', contribute: 'Contribuir',
  viewPayouts: 'Ver pagos', startGroup: 'Iniciar grupo', inviteMembers: 'Invitar miembros',
  inviteHint: 'Comparte este enlace con quien quieras invitar. Necesitarán aprobación del administrador.',
  generateInviteLink: '🔗 Generar enlace de invitación', copy: 'Copiar', copied: '✓ Copiado!',
  name: 'Nombre', phone: 'Teléfono', trustScoreCol: 'Puntuación', status: 'Estado',
  action: 'Acción', approve: 'Aprobar', you: '(Tú)', groupNotFound: 'Grupo no encontrado',
  editProfile: 'Editar perfil', fullName: 'Nombre completo', saveChanges: 'Guardar cambios',
  saving: 'Guardando...', profileUpdated: '¡Perfil actualizado!',
  updateFailed: 'Error al actualizar', accountInfo: 'Info de cuenta', verified: 'Verificado',
  yes: '✓ Sí', no: '✗ No', signOut: 'Cerrar sesión',
  notificationsTitle: 'Notificaciones', noNotifications: 'Sin notificaciones aún',
  welcomeBack: 'Bienvenido de nuevo', signInSubtitle: 'Inicia sesión en tu cuenta',
  phoneNumber: 'Número de teléfono', password: 'Contraseña', signingIn: 'Iniciando sesión...',
  signIn: 'Iniciar sesión', noAccount: '¿No tienes cuenta?', register: 'Registrarse',
  createAccount: 'Crear cuenta', registerSubtitle: 'Únete a Via y ahorra juntos',
  passwordOptional: 'Contraseña (opcional)', passwordHint: 'Mín. 6 caracteres',
  registering: 'Registrando...', alreadyHaveAccount: '¿Ya tienes cuenta?',
  verifyPhone: 'Verificar teléfono', otpSentTo: 'Ingresa el código de 6 dígitos enviado a',
  otpCode: 'Código OTP', verifying: 'Verificando...', verify: 'Verificar',
  backToLogin: '← Volver al inicio', cancel: 'Cancelar', creating: 'Creando...',
  makeContribution: 'Hacer contribución', amountToPay: 'Monto a pagar',
  selectPaymentMethod: 'Seleccionar método de pago', processing: 'Procesando...',
  pay: 'Pagar', paymentFailed: 'Pago fallido',
  payoutQueue: 'Cola de pagos', noPayoutYet: 'Sin cola de pagos aún.',
  settingsTitle: 'Configuración', appearance: 'Apariencia', theme: 'Tema',
  themeDesc: 'Cambiar entre modo claro y oscuro', colorPalette: 'Paleta de colores',
  lightMode: 'MODO CLARO', darkMode: 'MODO OSCURO', account: 'Cuenta',
  logOut: 'Cerrar sesión', logOutConfirm: '¿Cerrar sesión?',
  logOutDesc: '¿Estás seguro de que quieres cerrar sesión?',
  yesLogOut: 'Sí, cerrar sesión', language: 'Idioma', languageDesc: 'Elige tu idioma preferido',
  chooseLanguage: 'Elige tu idioma',
};

const pt = {
  dashboard: 'Painel', groups: 'Grupos', notifications: 'Notificações',
  profile: 'Perfil', settings: 'Configurações',
  hello: 'Olá', trustScore: 'Pontuação de confiança', totalGroups: 'Total de grupos',
  active: 'Ativo', forming: 'Formando', role: 'Função', myGroups: 'Meus grupos',
  createGroup: '+ Criar grupo', browseGroups: 'Explorar grupos',
  noGroupsYet: 'Ainda sem grupos.', loading: 'Carregando...',
  verifyBannerTitle: 'Complete sua verificação de identidade',
  verifyBannerDesc: 'Você precisa verificar seu ID ou passaporte antes de criar grupos, entrar ou contribuir.',
  verifyNow: 'Verificar agora',
  allGroups: 'Todos os grupos', searchGroups: 'Pesquisar grupos...', noGroupsFound: 'Nenhum grupo encontrado',
  members: 'membros', back: '← Voltar', joinGroup: 'Entrar', contribute: 'Contribuir',
  viewPayouts: 'Ver pagamentos', startGroup: 'Iniciar grupo', inviteMembers: 'Convidar membros',
  inviteHint: 'Compartilhe este link com quem quiser convidar.',
  generateInviteLink: '🔗 Gerar link de convite', copy: 'Copiar', copied: '✓ Copiado!',
  name: 'Nome', phone: 'Telefone', trustScoreCol: 'Pontuação', status: 'Status',
  action: 'Ação', approve: 'Aprovar', you: '(Você)', groupNotFound: 'Grupo não encontrado',
  editProfile: 'Editar perfil', fullName: 'Nome completo', saveChanges: 'Salvar alterações',
  saving: 'Salvando...', profileUpdated: 'Perfil atualizado!',
  updateFailed: 'Falha na atualização', accountInfo: 'Info da conta', verified: 'Verificado',
  yes: '✓ Sim', no: '✗ Não', signOut: 'Sair',
  notificationsTitle: 'Notificações', noNotifications: 'Sem notificações ainda',
  welcomeBack: 'Bem-vindo de volta', signInSubtitle: 'Entre na sua conta',
  phoneNumber: 'Número de telefone', password: 'Senha', signingIn: 'Entrando...',
  signIn: 'Entrar', noAccount: 'Não tem conta?', register: 'Registrar',
  createAccount: 'Criar conta', registerSubtitle: 'Junte-se ao Via e economize juntos',
  passwordOptional: 'Senha (opcional)', passwordHint: 'Mín. 6 caracteres',
  registering: 'Registrando...', alreadyHaveAccount: 'Já tem conta?',
  verifyPhone: 'Verificar telefone', otpSentTo: 'Digite o código de 6 dígitos enviado para',
  otpCode: 'Código OTP', verifying: 'Verificando...', verify: 'Verificar',
  backToLogin: '← Voltar ao login', cancel: 'Cancelar', creating: 'Criando...',
  makeContribution: 'Fazer contribuição', amountToPay: 'Valor a pagar',
  selectPaymentMethod: 'Selecionar método de pagamento', processing: 'Processando...',
  pay: 'Pagar', paymentFailed: 'Pagamento falhou',
  payoutQueue: 'Fila de pagamentos', noPayoutYet: 'Sem fila de pagamentos ainda.',
  settingsTitle: 'Configurações', appearance: 'Aparência', theme: 'Tema',
  themeDesc: 'Alternar entre modo claro e escuro', colorPalette: 'Paleta de cores',
  lightMode: 'MODO CLARO', darkMode: 'MODO ESCURO', account: 'Conta',
  logOut: 'Sair', logOutConfirm: 'Sair?',
  logOutDesc: 'Tem certeza que deseja sair do Via?',
  yesLogOut: 'Sim, sair', language: 'Idioma', languageDesc: 'Escolha seu idioma preferido',
  chooseLanguage: 'Escolha seu idioma',
};

const ar = {
  dashboard: 'لوحة التحكم', groups: 'المجموعات', notifications: 'الإشعارات',
  profile: 'الملف الشخصي', settings: 'الإعدادات',
  hello: 'مرحباً', trustScore: 'درجة الثقة', myGroups: 'مجموعاتي',
  createGroup: '+ إنشاء مجموعة', loading: 'جار التحميل...',
  members: 'أعضاء', back: '← رجوع', joinGroup: 'انضم', contribute: 'ساهم',
  viewPayouts: 'عرض المدفوعات', startGroup: 'بدء المجموعة',
  name: 'الاسم', phone: 'الهاتف', status: 'الحالة', approve: 'موافقة',
  editProfile: 'تعديل الملف', fullName: 'الاسم الكامل', saveChanges: 'حفظ التغييرات',
  saving: 'جار الحفظ...', yes: '✓ نعم', no: '✗ لا', signOut: 'تسجيل الخروج',
  welcomeBack: 'مرحباً بعودتك', signInSubtitle: 'سجّل الدخول إلى حسابك',
  phoneNumber: 'رقم الهاتف', password: 'كلمة المرور', signingIn: 'جار تسجيل الدخول...',
  signIn: 'تسجيل الدخول', noAccount: 'ليس لديك حساب؟', register: 'تسجيل',
  createAccount: 'إنشاء حساب', registerSubtitle: 'انضم إلى Via وادخر معاً',
  passwordOptional: 'كلمة المرور (اختياري)', passwordHint: '٦ أحرف على الأقل',
  registering: 'جار التسجيل...', alreadyHaveAccount: 'لديك حساب بالفعل؟',
  otpCode: 'رمز OTP', verifying: 'جار التحقق...', verify: 'تحقق',
  cancel: 'إلغاء', pay: 'ادفع', processing: 'جار المعالجة...',
  settingsTitle: 'الإعدادات', language: 'اللغة', languageDesc: 'اختر لغتك المفضلة',
  logOut: 'تسجيل الخروج', account: 'الحساب',
  chooseLanguage: 'اختر لغتك',
};

const sw = {
  dashboard: 'Dashibodi', groups: 'Vikundi', notifications: 'Arifa',
  profile: 'Wasifu', settings: 'Mipangilio',
  hello: 'Habari', trustScore: 'Alama ya Uaminifu', myGroups: 'Vikundi Vyangu',
  createGroup: '+ Unda Kikundi', loading: 'Inapakia...',
  members: 'wanachama', back: '← Rudi', joinGroup: 'Jiunge', contribute: 'Changia',
  viewPayouts: 'Ona Malipo', startGroup: 'Anza Kikundi',
  name: 'Jina', phone: 'Simu', status: 'Hali', approve: 'Idhinisha',
  editProfile: 'Hariri Wasifu', fullName: 'Jina Kamili', saveChanges: 'Hifadhi Mabadiliko',
  saving: 'Inahifadhi...', yes: '✓ Ndiyo', no: '✗ Hapana', signOut: 'Toka',
  welcomeBack: 'Karibu Tena', signInSubtitle: 'Ingia kwenye akaunti yako',
  phoneNumber: 'Nambari ya Simu', password: 'Nenosiri', signingIn: 'Inaingia...',
  signIn: 'Ingia', noAccount: 'Huna akaunti?', register: 'Jisajili',
  createAccount: 'Fungua Akaunti', registerSubtitle: 'Jiunge na Via na uokoe pamoja',
  passwordOptional: 'Nenosiri (hiari)', passwordHint: 'Herufi 6 au zaidi',
  registering: 'Inasajili...', alreadyHaveAccount: 'Una akaunti tayari?',
  otpCode: 'Nambari ya OTP', verifying: 'Inathibitisha...', verify: 'Thibitisha',
  cancel: 'Ghairi', pay: 'Lipa', processing: 'Inashughulikia...',
  settingsTitle: 'Mipangilio', language: 'Lugha', languageDesc: 'Chagua lugha unayopendelea',
  logOut: 'Toka', account: 'Akaunti',
  chooseLanguage: 'Chagua lugha yako',
};

const ha = {
  dashboard: 'Allon Sarrafa', groups: 'Ƙungiyoyi', notifications: 'Sanarwa',
  profile: 'Bayanan Kai', settings: 'Saituna',
  hello: 'Sannu', trustScore: 'Maki na Amana', myGroups: 'Ƙungiyoyina',
  createGroup: '+ Ƙirƙiri Ƙungiya', loading: 'Ana lodi...',
  members: 'mambobi', back: '← Koma', joinGroup: 'Shiga', contribute: 'Ba da gudummawa',
  viewPayouts: 'Duba Biyan Kuɗi', startGroup: 'Fara Ƙungiya',
  name: 'Suna', phone: 'Waya', status: 'Matsayi', approve: 'Amince',
  editProfile: 'Gyara Bayanan Kai', fullName: 'Cikakken Suna', saveChanges: 'Ajiye Canje-canje',
  saving: 'Ana ajiyewa...', yes: '✓ Ee', no: '✗ A\'a', signOut: 'Fita',
  welcomeBack: 'Barka da Dawowar', signInSubtitle: 'Shiga asusunka',
  phoneNumber: 'Lambar Waya', password: 'Kalmar Sirri', signingIn: 'Ana shiga...',
  signIn: 'Shiga', noAccount: 'Ba ka da asusu?', register: 'Yi rajista',
  createAccount: 'Ƙirƙiri Asusu', registerSubtitle: 'Shiga Via ka ajiye tare',
  passwordOptional: 'Kalmar Sirri (zaɓi)', passwordHint: 'Haruffa 6 ko fiye',
  registering: 'Ana rajista...', alreadyHaveAccount: 'Kana da asusu?',
  otpCode: 'Lambar OTP', verifying: 'Ana tabbatarwa...', verify: 'Tabbatar',
  cancel: 'Soke', pay: 'Biya', processing: 'Ana sarrafa...',
  settingsTitle: 'Saituna', language: 'Harshe', languageDesc: 'Zaɓi harshen da kake so',
  logOut: 'Fita', account: 'Asusu',
  chooseLanguage: 'Zaɓi harshenka',
};

const yo = {
  dashboard: 'Pẹpẹ Iṣakoso', groups: 'Àwọn Ẹgbẹ', notifications: 'Ìwífún',
  profile: 'Profaili', settings: 'Ètò',
  hello: 'Ẹ káàbọ̀', trustScore: 'Ìdánilójú Ìgbẹ́kẹ̀lé', myGroups: 'Àwọn Ẹgbẹ Mi',
  createGroup: '+ Ṣẹ̀dá Ẹgbẹ', loading: 'Ń gbé...',
  members: 'àwọn ọmọ ẹgbẹ', back: '← Padà', joinGroup: 'Darapọ̀', contribute: 'Ṣe Àfikún',
  viewPayouts: 'Wo Àwọn Ìsanwó', startGroup: 'Bẹ̀rẹ̀ Ẹgbẹ',
  name: 'Orúkọ', phone: 'Fóònù', status: 'Ipò', approve: 'Fọwọ́ sí',
  editProfile: 'Ṣàtúnṣe Profaili', fullName: 'Orúkọ Kíkún', saveChanges: 'Tọ́jú Àwọn Ìyípadà',
  saving: 'Ń tọ́jú...', yes: '✓ Bẹ́ẹ̀ni', no: '✗ Rárá', signOut: 'Jáde',
  welcomeBack: 'Ẹ káàbọ̀ padà', signInSubtitle: 'Wọlé sí àkáǹtì rẹ',
  phoneNumber: 'Nọ́mbà Fóònù', password: 'Ọ̀rọ̀ Aṣínà', signingIn: 'Ń wọlé...',
  signIn: 'Wọlé', noAccount: 'Kò sí àkáǹtì?', register: 'Forúkọsílẹ̀',
  createAccount: 'Ṣẹ̀dá Àkáǹtì', registerSubtitle: 'Darapọ̀ mọ́ Via kí ẹ pamọ́ papọ̀',
  passwordOptional: 'Ọ̀rọ̀ Aṣínà (àṣàyàn)', passwordHint: 'Ìwé 6 tàbí jù bẹ́ẹ̀ lọ',
  registering: 'Ń forúkọsílẹ̀...', alreadyHaveAccount: 'Ó ti ní àkáǹtì?',
  otpCode: 'Kóòdù OTP', verifying: 'Ń ṣàyẹ̀wò...', verify: 'Ṣàyẹ̀wò',
  cancel: 'Fagilé', pay: 'San', processing: 'Ń ṣiṣẹ́...',
  settingsTitle: 'Ètò', language: 'Èdè', languageDesc: 'Yan èdè tí o fẹ́',
  logOut: 'Jáde', account: 'Àkáǹtì',
  chooseLanguage: 'Yan èdè rẹ',
};

const LanguageContext = createContext({});

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('lang') || 'en');

  const t = (key) => {
    const dicts = { en, fr, es, pt, ar, sw, ha, yo };
    const dict = dicts[lang] || en;
    return dict[key] || en[key] || key;
  };

  const setLanguage = (l) => { setLang(l); localStorage.setItem('lang', l); };

  return (
    <LanguageContext.Provider value={{ lang, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
